name=U8g2
version=2.33.15
author=olikraus
maintainer=olikraus
sentence=U8g2: Monochrome OLED, LCD and ePaper Library
paragraph=U8g2 is a monochrome graphics library for embedded systems with simple and complex displays.
category=Display
url=https://github.com/olikraus/U8g2_Arduino
architectures=*