name=Adafruit BME280 Library
version=2.2.2
author=Adafruit
maintainer=Adafruit <info@adafruit.com>
sentence=Arduino library for BME280 sensors
paragraph=This is a library for the BME280 humidity, temperature and pressure sensor.
category=Sensors
url=https://github.com/adafruit/Adafruit_BME280_Library
architectures=*