name=PubSubClient
version=2.8.0
author=Nick O'Leary
maintainer=Nick O'Leary
sentence=MQTT library for Arduino
paragraph=This library provides a client for MQTT messaging protocol.
category=Communication
url=https://github.com/knolleary/pubsubclient
architectures=*